baseurl = "http://www.ivoidwarranties.tech/"
languageCode = "en-us"
title = "KCSEC"
  disqusShortname = "kcivwdq"
# Enable Google Analytics by entering your tracking code - NEED TO DO
# googleAnalytics = ""
paginate = 50
theme = "sublime-hugo"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "K.C"
	description = "KSEC Security Blog"
	copyright = "KCSEC"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Contact Info"
	bio = "Idea for improvements?"
	bio2 = "Contact me for topic or tutorial requests."
	subscribe = "Subscribe Here "
	followme = "Contact"

	# Enable Google search
	search_enabled = "True"
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "IVW@kcsec.tech"
		url = "mailto:IVW@kcsec.tech"
